kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: deploy-engine
  namespace: airgent
  labels:
    app: actionengine
    release: phase1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: actionengine
        release: phase1
    spec:
      volumes:
        - name: sharedata
          emptyDir: {}
      containers:
        - name: engine
          image: airta/actionengine:latest
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 500Mi
          ports:
            - name: rest
              containerPort: 8201
          volumeMounts:
            - name: sharedata
              mountPath: /data
        - name: sitemap
          image: airta/airsitemap:latest
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 500Mi
          ports:
            - name: http
              containerPort: 8202
          volumeMounts:
            - name: sharedata
              mountPath: /usr/share/nginx/html/data
---
apiVersion: v1
kind: Service
metadata:
  name: engine-service
  namespace: airgent
spec:
  ports:
    - name: rest
      port: 8201
      targetPort: 8201
    - name: http
      port: 8202
      targetPort: 8202
  selector:
    app: actionengine
  type: NodePort